[WIP] Perfect Periodic BC
awslabs/palace pull request #266
Opened 2024-06-13 22:04 UTC by LeilaGhaffari

This PR is aiming at adding support for perfect periodic BC.
I have added two meshes in [examples/cube/](https://github.com/LeilaGhaffari/palace-lg/tree/lgh/periodic-bc/examples/cube). Both have 3 elements since mfem didn't let me create a unit cell cube. `cube.mesh` is a regular cube and `cube_periodic.mesh` is periodic.

@sebastiangrimberg , are the boundary conditioned specified [here](https://github.com/LeilaGhaffari/palace-lg/blob/dda0768bc40dc680d157eeaf3b33cafa8909299a/examples/cube/cube_pec.json#L41) and [here](https://github.com/LeilaGhaffari/palace-lg/blob/dda0768bc40dc680d157eeaf3b33cafa8909299a/examples/cube/cube_periodic.json#L40) making sense?

2024-08-13 19:23 UTC, LeilaGhaffari commented
@hughcars , I don't seem to have necessary permissions to add reviewers but I think this is in good shape for review. I would still need to add support for lexographic elements but that shouldn't block the review. Thanks!

2024-08-19 18:06 UTC, hughcars commented on scripts/schema/config/boundaries.json
> +    },
I don't believe this is correct: running `./scripts/validate-config examples/cube/cube_periodic_xy_user.json` from the root folder gives an error. This should also be updated once the interface is in terms of pairs of attributes `[[1,2], [3,4], [5,6]]` for instance in the case of the cube.

2024-08-19 22:50 UTC, LeilaGhaffari commented on palace/fem/libceed/restriction.cpp
> +  face_tr.Reset();
True, I had copy/pasted from a function where `face_tr` is returned!

2024-08-20 20:00 UTC, LeilaGhaffari commented on palace/utils/configfile.hpp
> +  std::vector<int> receiver_attributes = {};
Per our conversation today, I'll leave the design as is for now.

2024-08-20 20:02 UTC, LeilaGhaffari commented on palace/utils/configfile.hpp
> +  std::vector<double> translation = {0.0, 0.0, 0.0};
I was thinking of populating the translation vector inside `LoadMesh()` when we add that functionality. In that case, Distance and Direction wouldn’t be required.

2024-08-30 21:22 UTC, hughcars requested changes
Almost done. The issue with the hex/prism/tet waveguide is going to mean the gmsh meshes need to be refined, cavity rebaselined and then the tables of the corresponding modes filled in. Additionally, do not need to remove the attributes on donor and receiver (and can patch mfem to not do the same as well) then we can add computing the power flux for each mode to the regression tests.

2024-09-03 21:40 UTC, hughcars commented
I've addressed all the issues here in https://github.com/awslabs/palace/tree/hughcars/periodic-bc including merging main in. I'm not sure how to merge those commits onto this branch, given it's originally from a fork. You can either merge them in, or I can open another PR from that branch. It should just be a fast forward from this branch.

2024-09-04 15:49 UTC, LeilaGhaffari commented
Thanks @hughcars for fixing the issues. I just pushed your fixes to this branch. Is there anything else I can help with before merging?

2024-09-04 20:34 UTC, hughcars commented
> Thanks @hughcars for fixing the issues. I just pushed your fixes to this branch. Is there anything else I can help with before merging?

I just read through it again and found a few small things I missed, there's one more commit on `hughcars/periodic-bc` then we're good to merge.

2024-09-04 20:55 UTC, LeilaGhaffari commented
> > Thanks @hughcars for fixing the issues. I just pushed your fixes to this branch. Is there anything else I can help with before merging?
> 
> I just read through it again and found a few small things I missed, there's one more commit on `hughcars/periodic-bc` then we're good to merge.

Just pushed it, thanks!

2024-09-04 21:29 UTC, hughcars approved these changes

2024-09-04 21:41 UTC, merged