Refactor measurement and printing for future features
awslabs/palace pull request #302
Opened 2024-11-19 23:48 UTC by phdum-a

Refactoring of measurement and printing system in preparation for multi-excitation support.
- Separates outs measurements (to be done in PostOperator only) from printing (to be done by Solvers)
- Printing is now change from Postpro functions into small printer classes which also hold a table of results, rather than printing row-by-row. (This is where multi-excitations will add extra columns).
- The output path is now handled using std::filesystem more consistently
- Measurements in PostOperator are now cached so that printers don't have to worry about that the getter functions might trigger an expensive calculation or one that requires MPI communication.
- Add PALACE_MFEM_USE_EXCEPTIONS build flag for unit tests, since catch can't test for aborts.
- Other small tweaks and improvements

Note: The output of all solvers after these changes should be _identical_ to the current output*, for easy testing. Changes which alter output will be in subsequent PRs.
[*With one trivial change in the logger for eigenvalues from \omega/2pi -> f]

2024-12-10 10:16 UTC, fedeinthemix commented
Hi, since you are refactoring the output format to support multi-excitations, I'd like to ask if would consider adding an option to output S-parameter files in [Touchstone](https://en.wikipedia.org/wiki/Touchstone_file) format. It's a de-facto standard in circuit simulators and beyond.

2024-12-10 17:47 UTC, phdum-a commented
> Hi, since you are refactoring the output format to support multi-excitations, I'd like to ask if would consider adding an option to output S-parameter files in [Touchstone](https://en.wikipedia.org/wiki/Touchstone_file) format. It's a de-facto standard in circuit simulators and beyond.

Dear @fedeinthemix,

Thank you very much for your suggestion. We'll have to think about it more, but right now we don't have plans to print touchstone files directly in Palace.

In cases where people require touchstone files, we have recommended writing a script that reads in the palace csv files from all the separate simulations (e.g. using pandas) and then prints it in the right form. You could also look at [scikit-rf](https://scikit-rf.readthedocs.io/en/v1.3.0/tutorials/Networks.html) that has a touchstone printer and parser. 

For Palace, we do want a consistant file formats with other measurements not covered by touchstone, like energy or fields. Also the touchstone spec does not quite cover some cases, like simulating only a subset of columns of the s-matrix.

Please let use know, if there is there anything you think we are missing something in the Palace output. For example, is there something in the touchstone file format / metadata that you can't find easily? 

Thanks!

2024-12-11 07:21 UTC, fedeinthemix commented
Dear @phdum-a,

Thank you for your answer. I thought that an option to output Touchstone files would be convenient since most RF/mmW passive circuits simulated with palace will probably be used in circuit simulators. But, I understand point, and, as you say, writing a conversion procedure is not a big deal.

Thanks again for your answer.

2025-01-07 17:49 UTC, hughcars requested changes
Generally looks pretty good. I have some changes I think need to be made at https://github.com/awslabs/palace/pull/325 from `hughcars/new_postpro`.

2025-01-22 00:14 UTC, phdum-a commented
Rebased onto main

2025-03-14 21:15 UTC, phdum-a commented on palace/models/postoperator.cpp
> +  ClearAllMeasurementCache();
Addressed in new templated PostOperator.

2025-03-14 21:19 UTC, phdum-a commented on palace/models/postoperator.hpp
> +  };
Addressed in new templated PostOperator. Optionals are now removed and measurement_cache is now just a workspace internal to PostOperator for dependent measurements.

2025-03-14 21:20 UTC, phdum-a commented on palace/models/postoperator.hpp
> +  WavePortOperator *wave_port_op = nullptr;
Now obsolete since PostOperator now contains a pointer to fem_op (Space, CurlCurl, or Laplace as appropriate).

2025-03-14 21:22 UTC, phdum-a commented on palace/models/postoperator.cpp
> +  Mpi::Barrier(GetComm());
Done.

2025-03-14 21:22 UTC, phdum-a commented on palace/utils/tablecsv.hpp
> +  // Future: allow int and other output, allow non-owning memeory via span
Done.

2025-03-14 21:41 UTC, phdum-a commented on palace/models/lumpedportoperator.cpp
> +  Mpi::Print("{}", fmt::to_string(buf));
The buffering is mostly there to simplify the conditional printing and make the code more readable.

Yes, that means that multiple lines are printed as once, as you said. However, I don't think that is such a big deal here since this doing any computation that could fail, where using the data as partial logging may be useful. In those cases, yes we should flush the buffer. (I think stdout is normally line buffered and stderr unbuffered but mpi may have custom options here; std::out may also keep more of a buffer)

2025-03-16 00:05 UTC, phdum-a commented on palace/utils/tablecsv.hpp
> +  // ----
Done

2025-03-16 00:06 UTC, phdum-a commented on palace/models/postoperator.hpp
>    // Postprocess the circuit voltage and current across lumped port index using the electric
Now obsolete

2025-03-16 00:06 UTC, phdum-a commented on palace/models/postoperator.cpp
>  }
Now obsolete.

2025-03-16 00:12 UTC, phdum-a commented on palace/drivers/basesolver.cpp
> -  }
There is the `MakeOutputFolder` in main.cpp now to ensure that the output dir exits and that it is writeable. I removed this check since `MakeOutputFolder` is always called in main, so it's not needed but it would not hurt to keep it either.

2025-03-16 00:14 UTC, phdum-a commented on palace/models/postoperator.hpp
> +  mutable MeasurementCache measurment_cache = {};
Fixed

2025-03-16 00:14 UTC, phdum-a commented on palace/models/postoperator.cpp
> +  // TODO: In multi-excittion PR we will gurantee that lumped & wave ports have unique idx
Obsolete.

2025-03-16 00:16 UTC, phdum-a commented on palace/models/postoperator.hpp
> +  void MeasureWavePorts() const;
Obsolete.

2025-03-16 00:18 UTC, phdum-a commented on palace/utils/tablecsv.hpp
> +  }
Right, you changed this below. I think this was the original `insert` interface for columns, but then I thought it better if we just pass the full Column and added that insert method overload. Now this once can just be perfect forwarding.

2025-03-17 18:59 UTC, phdum-a commented on palace/drivers/basesolver.hpp
> +  };
Obsolete in current code.

The bools were added for code clarity. The idea above was as follows:
- I thought a caller may want to disable `do_measurement` hence it was passed in the ctor. In the current code this option is removed, everything is printed that can be printed.
- In the ctor, the classes had a single point where they defined restrictions on when something should be printed. E.g. right now s-parameters are not printed in both lumped and wave ports exists. This condition should be written only once — a bool or simple function — rather than repeating it in different if statements. So that if that conditional is changed it is done once and without error. [In the current code this idea also holds true, although the implementation is different].

2025-03-17 22:27 UTC, phdum-a commented on palace/drivers/basesolver.hpp
>    // Common surface postprocessing for all simulation types.
Many more comments now added with general explanation in PostOperator.

2025-03-17 22:27 UTC, phdum-a commented on palace/utils/tablecsv.hpp
> +  unsigned long file_append_curser = -1;
Done.

2025-03-17 22:29 UTC, phdum-a commented on palace/drivers/basesolver.cpp
> -  }
We also decided (in a breaking change) that we should required a output directory in the config file. Then the json metadata and csv files with always be written — i.e. you can just write to stdout anymore.

2025-03-17 22:43 UTC, phdum-a commented on palace/utils/tablecsv.hpp
> +#define PALACE_UTILS_TABLECSV_HPP
1. I don't have strong feelings on this. It's a tiny class which is only used in a few selective places. So I don't have any problem leaving it in a header, but feel free to move them to a separate cpp if you want.

2. Again, I don't have strong feelings —I just did it like this for expediency. We do use the table class to print stdout logging. Admittedly that is currently only done once for eigenmodes. In that case we do want different col formatting options than for the file printing, so we can't just recycle the csv printer output. There may be other places where we want a table printer with the file handling. 

If you really bothered by the `.table` everywhere then: (a) you could merge them as you suggest but then have some logic to use the table "file free" so it does not print to file if it does not have an associated file (b) You could have a forwarding interface in the `TableWithCSV` class that passes args to `.table`.

2025-03-24 22:35 UTC, hughcars reviewed
Generally looks good to me. Caught some minor bugs, all my suggested changes are on `hughcars/new_postpro` https://github.com/awslabs/palace/pull/356. So feel free to merge that if you agree, then we're good to go.

2025-03-24 22:35 UTC, hughcars commented on palace/models/postoperatorcsv.cpp
> +  // TODO(C++20): Make this a filterd iterator in LumpedPortOp
filtered

2025-03-24 23:22 UTC, phdum-a commented on palace/models/postoperator.cpp
> +    auto field = V ? *V : *E;
Yes, good catch!

2025-03-24 23:22 UTC, phdum-a commented on palace/models/postoperator.cpp
> +      // Get previously computed data: should never fail as defind by MeasureWavePorts.
Obsolete comment.

2025-03-24 23:25 UTC, phdum-a commented on palace/models/postoperatorcsv.cpp
> +                           1 + 2 * post_op->surf_post_op.flux_surfs.size());
Thanks! This is done in ProbeE,ProbeB but I missed this one.

2025-03-24 23:25 UTC, phdum-a commented on palace/models/postoperator.cpp
> +      auto freq_re = measurement_cache.freq.real();  // TODO: Fix
Obsolete placeholder comment; can remove.

2025-03-25 17:22 UTC, hughcars approved these changes

2025-03-25 17:22 UTC, merged