Complex-valued coarse preconditioner
awslabs/palace pull request #310
Opened 2024-12-10 20:33 UTC by simlapointe

This change uses the true complex-valued system matrix for the coarse solve (sparse direct solve) instead of the real-valued approximation. We still use the real-valued sparse matrix libraries and pass the 2x2 block matrix `[A_r -A_i; A_i A_r]` to solver. Further speedup could be obtained by using complex-valued sparse matrix libraries, but this would require a bit more work, including MFEM interfaces.

2024-12-18 18:22 UTC, hughcars requested changes
Tried it out with MGMaxLevels 1 on the cavity, great that the ksp solves in a single iteration now (with an exact preconditioner effectively). 

I pushed a branch with some suggested changes `hughcars/complex-pc`:
1. A new `SetSubVector` to avoid the use of idx.
2. Reordering some callsites to put IoData ahead of all across the code base. This then means the variadic function avoids using an extra argument for data that was already being pass in as part of `IoData`.

2024-12-18 18:41 UTC, simlapointe commented on palace/linalg/solver.cpp
> +      }
Nice!

2024-12-18 18:41 UTC, simlapointe commented on scripts/schema/config/solver.json
> +          "ComplexCoarseSolve": {"type": "boolean"},
My bad.

2024-12-18 18:42 UTC, simlapointe commented on palace/linalg/ksp.cpp
> +                                                        fespaces.GetNumLevels() > 1, print);
Yes, I like your suggestion.

2024-12-24 14:27 UTC, hughcars approved these changes

2024-12-30 17:51 UTC, merged