Support Floquet periodic boundary conditions
awslabs/palace pull request #314
Opened 2024-12-13 16:16 UTC by simlapointe

- Support Floquet boundary conditions by incorporating the phase delay into Maxwell's equations and solving the modified PDE with periodic boundary conditions.
- Automatically detect periodic boundary transformations.
- Support both translation and rotation transformations.

2025-01-30 23:19 UTC, hughcars requested changes
Looking pretty good, I think there are a few larger changes to take care of first
1) FP should be part of K, given it has no omega dependence in its construction unlike A2. This will simplify loads of things 
2) The muinv kx should be in the MaterialOperator, (doing this neatly will mean adding the ability to use transpose coefficients in the ceed context)
3) The geodata.cpp can be shortened and simplified some, I have some initial work on doing this in `hughcars/periodic-bc`, but I'm sure once you get started you'll probably see even more things to do. The basic thing is a mixing assumptions on sdim and no assumptions on sdim.

2025-01-30 23:19 UTC, hughcars commented on palace/utils/configfile.cpp
> +    }
Use full names for the variables.

2025-01-30 23:19 UTC, hughcars commented on palace/utils/configfile.hpp
>    std::array<double, 3> translation = {0.0, 0.0, 0.0};
Can this be encoded into the affine transformation? Given it's going to overlap with the final column in terms of data. I.e. if there's a translation, set the rotation piece to identity and fill the translation in.

2025-01-30 23:19 UTC, hughcars commented on palace/utils/geodata.cpp
> +  }
If the translation is written to the affine transformation variable in configfile.cpp, this can be shortened to
```
mfem::DenseMatrix transformation(4);
std::copy(data.affine_transform.begin(), data.affine_transform.end(), transformation.begin());
transformation.Transpose();
if (transformation.Norml2() == 0.0)
{
  ...
```

2025-01-30 23:19 UTC, hughcars commented on palace/drivers/drivensolver.cpp
>  #include "fem/errorindicator.hpp"
Missing the correction on the adaptive branch.

2025-01-30 23:19 UTC, hughcars commented on palace/linalg/floquetcorrection.cpp
> +template class FloquetCorrSolver<ComplexVector>;
Is this ever going to be applied to a real valued case?

2025-02-04 19:33 UTC, simlapointe commented on docs/src/examples/cylinder.md
> +boundaries in the X/Y/Z directions.
I compared the cylindrical waveguide modes (as well as a rectangular waveguide and a nail/pillar) against Comsol and they all matched so I feel confident about it, but I'll see if I can derive analytical modes for the Floquet case.

2025-02-04 19:34 UTC, simlapointe commented on docs/src/guide/boundaries.md
> +translation or rotation. Periodicity in *Palace* is also supported through meshes generated
I tested the pure rotation with an annulus wedge and the rotation + translation case with a helical case.

2025-02-04 19:36 UTC, simlapointe commented on palace/fem/libceed/operator.hpp
> +
I added it for some tests and forgot to remove. Got rid of it now.

2025-02-04 19:37 UTC, simlapointe commented on palace/fem/qfunctions/22/utils_22_qf.h
> +  C[3] = B[1] * A[2] + B[3] * A[3];
I'm leaving it as is in this PR but agree it might be worth profiling.

2025-02-04 19:38 UTC, simlapointe commented on palace/utils/geodata.cpp
> +                                           const double &mesh_dim, const double &tol = 1e-6)
Yes, you're right. I incorporated your suggestions, with slight changes as they were not working as is.

2025-02-04 19:39 UTC, simlapointe commented on palace/models/spaceoperator.hpp
I initially thought it was better to have it as an extra term but I now agree with you. Added it into K.

2025-02-04 19:40 UTC, simlapointe commented on palace/utils/configfile.hpp
>    std::array<double, 3> translation = {0.0, 0.0, 0.0};
Yes, good suggestion.

2025-02-04 19:40 UTC, simlapointe commented on palace/linalg/floquetcorrection.cpp
> +template class FloquetCorrSolver<ComplexVector>;
No, I removed the real case.

2025-02-04 19:41 UTC, simlapointe commented on palace/models/periodicboundaryoperator.cpp
> +PeriodicBoundaryOperator::PeriodicBoundaryOperator(const IoData &iodata,
Yes, good point. I got rid of PeriodicBoundaryOperator and moved the relevant code into MaterialOperator.

2025-02-04 19:42 UTC, simlapointe commented on palace/drivers/eigensolver.cpp
> +  }
Now using `mat_op.HasWaveVector()`

2025-02-04 19:43 UTC, simlapointe commented on palace/drivers/eigensolver.cpp
> +  if (iodata.solver.linear.divfree_max_it > 0 && !FP)
Can now use `mat_op.HasWaveVector()`

2025-02-07 23:11 UTC, hughcars requested changes
Some minor typos, and one further simplification of the coefficient handling for the floquet hermitian term then we're good to go.

2025-02-07 23:11 UTC, hughcars commented on palace/fem/integrator.hpp
> +  bool transpose;
Having the transpose for every single integrator is slightly overkill for the use case here, but I appreciate keeping consistency of behaviour across all the integrators. I was considering if it could or should be folded into the `Q`, but this is better.

2025-02-07 23:11 UTC, hughcars commented on palace/models/spaceoperator.cpp
> +                                            MaterialPropertyCoefficient &fc)
The only reason there needs to be two coefficients here, is because they are being added in with +1 and -1 coefficients. If you change the `MixedVectorWeakCurlIntegrator` to `a(u, v) = - (Q u, curl v)` similar to how `MixedVectorWeakDivergenceIntegrator` uses the negative `Q`, then there only needs to be one coefficient and the hermitian nature of the operators is really apparent. This would mean adding the `-1` coefficent to the `PopulateCoefficientContext` call similar to `MixedVectorWeakDivergenceIntegrator`.  This would mean changing some of the unit tests against mfem most likely too, but will reduce the LOC further.

2025-02-10 16:12 UTC, simlapointe commented on palace/drivers/eigensolver.cpp
> +      floquet_corr->AddMult(E, B, 1.0 / omega);
Should be the same (+) everywhere, forgot to change one of the driven ones.

2025-02-10 16:13 UTC, simlapointe commented on palace/models/materialoperator.cpp
> +  }
I'm good with allowing the sum.

2025-02-10 16:13 UTC, simlapointe commented on palace/utils/geodata.cpp
> +template <typename T>
It's still used in two places with different inputs (array<int> and unordered_set<int>) so I kept the template.

2025-02-10 16:15 UTC, simlapointe commented on palace/models/spaceoperator.cpp
> +                                            MaterialPropertyCoefficient &fc)
I'm good with that, made the changes.

2025-02-11 20:03 UTC, hughcars approved these changes

2025-02-11 21:11 UTC, merged